[dotenv@17.2.2] injecting env (5) from .env -- tip: ⚙️  override existing env vars with { override: true }
go model :  gpt-4o
error in model :  gpt-4o APIConnectionError: Connection error.
    at OpenAI.makeRequest (/workspaces/tg-parser/node_modules/openai/src/client.ts:656:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async test (/workspaces/tg-parser/src/utils/ai/test/test_ai.ts:7:19) {
  status: undefined,
  headers: undefined,
  requestID: undefined,
  error: undefined,
  code: undefined,
  param: undefined,
  type: undefined,
  cause: TypeError: fetch failed
      at node:internal/deps/undici/undici:13510:13
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async OpenAI.fetchWithTimeout (/workspaces/tg-parser/node_modules/openai/src/client.ts:780:14)
      at async OpenAI.makeRequest (/workspaces/tg-parser/node_modules/openai/src/client.ts:611:22)
      at async test (/workspaces/tg-parser/src/utils/ai/test/test_ai.ts:7:19) {
    [cause]: AggregateError [ECONNREFUSED]: 
        at internalConnectMultiple (node:net:1134:18)
        at afterConnectMultiple (node:net:1715:7) {
      code: 'ECONNREFUSED',
      [errors]: [Array]
    }
  }
}
go model :  gpt-4.1
error in model :  gpt-4.1 APIConnectionError: Connection error.
    at OpenAI.makeRequest (/workspaces/tg-parser/node_modules/openai/src/client.ts:656:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async test (/workspaces/tg-parser/src/utils/ai/test/test_ai.ts:7:19) {
  status: undefined,
  headers: undefined,
  requestID: undefined,
  error: undefined,
  code: undefined,
  param: undefined,
  type: undefined,
  cause: TypeError: fetch failed
      at node:internal/deps/undici/undici:13510:13
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async OpenAI.fetchWithTimeout (/workspaces/tg-parser/node_modules/openai/src/client.ts:780:14)
      at async OpenAI.makeRequest (/workspaces/tg-parser/node_modules/openai/src/client.ts:611:22)
      at async test (/workspaces/tg-parser/src/utils/ai/test/test_ai.ts:7:19) {
    [cause]: AggregateError [ECONNREFUSED]: 
        at internalConnectMultiple (node:net:1134:18)
        at afterConnectMultiple (node:net:1715:7) {
      code: 'ECONNREFUSED',
      [errors]: [Array]
    }
  }
}
go model :  gpt-4
error in model :  gpt-4 APIConnectionError: Connection error.
    at OpenAI.makeRequest (/workspaces/tg-parser/node_modules/openai/src/client.ts:656:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async test (/workspaces/tg-parser/src/utils/ai/test/test_ai.ts:7:19) {
  status: undefined,
  headers: undefined,
  requestID: undefined,
  error: undefined,
  code: undefined,
  param: undefined,
  type: undefined,
  cause: TypeError: fetch failed
      at node:internal/deps/undici/undici:13510:13
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async OpenAI.fetchWithTimeout (/workspaces/tg-parser/node_modules/openai/src/client.ts:780:14)
      at async OpenAI.makeRequest (/workspaces/tg-parser/node_modules/openai/src/client.ts:611:22)
      at async test (/workspaces/tg-parser/src/utils/ai/test/test_ai.ts:7:19) {
    [cause]: AggregateError [ECONNREFUSED]: 
        at internalConnectMultiple (node:net:1134:18)
        at afterConnectMultiple (node:net:1715:7) {
      code: 'ECONNREFUSED',
      [errors]: [Array]
    }
  }
}
go model :  gpt-4o-mini
error in model :  gpt-4o-mini APIConnectionError: Connection error.
    at OpenAI.makeRequest (/workspaces/tg-parser/node_modules/openai/src/client.ts:656:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async test (/workspaces/tg-parser/src/utils/ai/test/test_ai.ts:7:19) {
  status: undefined,
  headers: undefined,
  requestID: undefined,
  error: undefined,
  code: undefined,
  param: undefined,
  type: undefined,
  cause: TypeError: fetch failed
      at node:internal/deps/undici/undici:13510:13
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async OpenAI.fetchWithTimeout (/workspaces/tg-parser/node_modules/openai/src/client.ts:780:14)
      at async OpenAI.makeRequest (/workspaces/tg-parser/node_modules/openai/src/client.ts:611:22)
      at async test (/workspaces/tg-parser/src/utils/ai/test/test_ai.ts:7:19) {
    [cause]: AggregateError [ECONNREFUSED]: 
        at internalConnectMultiple (node:net:1134:18)
        at afterConnectMultiple (node:net:1715:7) {
      code: 'ECONNREFUSED',
      [errors]: [Array]
    }
  }
}
go model :  gpt-3.5-turbo
error in model :  gpt-3.5-turbo APIConnectionError: Connection error.
    at OpenAI.makeRequest (/workspaces/tg-parser/node_modules/openai/src/client.ts:656:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async test (/workspaces/tg-parser/src/utils/ai/test/test_ai.ts:7:19) {
  status: undefined,
  headers: undefined,
  requestID: undefined,
  error: undefined,
  code: undefined,
  param: undefined,
  type: undefined,
  cause: TypeError: fetch failed
      at node:internal/deps/undici/undici:13510:13
      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
      at async OpenAI.fetchWithTimeout (/workspaces/tg-parser/node_modules/openai/src/client.ts:780:14)
      at async OpenAI.makeRequest (/workspaces/tg-parser/node_modules/openai/src/client.ts:611:22)
      at async test (/workspaces/tg-parser/src/utils/ai/test/test_ai.ts:7:19) {
    [cause]: AggregateError [ECONNREFUSED]: 
        at internalConnectMultiple (node:net:1134:18)
        at afterConnectMultiple (node:net:1715:7) {
      code: 'ECONNREFUSED',
      [errors]: [Array]
    }
  }
}
